### ISSUE TITLE
Incorrect Canonical Preventing Indexing

### ISSUE THREAD

**Issue by excentrickristy** [virtua-tech/jakartaee-tutorial-playbook#22]
I noticed today that the canonical for the tutorial page is set incorrectly, pointing to a page that doesn't exist:
<img width="1280" alt="image" src="https://github.com/jakartaee/jakartaee-documentation/assets/73264129/db6ddb0b-fd90-4c09-8d45-02118ca24dff">

This means that the new tutorial page has not been indexed and can't be found on search. Can we have the canonical tag set to point to the URL please?

**Comment by kito99** [comment]
Thanks @excentrickristy! 

@jhammen want to tackle this one? Looks pretty simple: https://docs.antora.org/antora/latest/playbook/site-url/.

**Comment by kito99** [comment]
thanks @jhammen! @excentrickristy this has been fixed and deployed.
